In [1]:
import numpy as np

In [2]:
a1=np.arange(1,11)
print(a1)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
print(f"Array {a1} element's datatype is {a1.dtype}")
print(f"Array {a1} element's shape is {a1.shape}")
print(f"Array {a1} elements datatype is {a1.}")

Array [ 1  2  3  4  5  6  7  8  9 10] element's datatype is int32
Array [ 1  2  3  4  5  6  7  8  9 10] element's shape is (10,)


In [11]:
a2=np.zeros((3,3,3))
print(a2)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [12]:
a2.shape

(3, 3, 3)

In [14]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.random.randint(5)

2

In [21]:
np.random.randint(0, 100, 5)

array([69, 10, 86, 95,  5])

In [24]:
b1=np.arange(1,11)
b2=np.arange(12,22)

sum=np.add(b1,b2)
mul=np.multiply(b1,b2)
diff=np.subtract(b1,b2)
div=np.divide(b1,b2)

print(f"b1 is {b1}")
print(f"b2 is {b2}")
print(f"Sum of b1 and b2 is {sum}")
print(f"Multiplication of b1 and b2 is {mul}")
print(f"Difference of b1 and b2 is {diff}")
print(f"Division of b1 and b2 is {div}")

b1 is [ 1  2  3  4  5  6  7  8  9 10]
b2 is [12 13 14 15 16 17 18 19 20 21]
Sum of b1 and b2 is [13 15 17 19 21 23 25 27 29 31]
Multiplication of b1 and b2 is [ 12  26  42  60  80 102 126 152 180 210]
Difference of b1 and b2 is [-11 -11 -11 -11 -11 -11 -11 -11 -11 -11]
Division of b1 and b2 is [0.08333333 0.15384615 0.21428571 0.26666667 0.3125     0.35294118
 0.38888889 0.42105263 0.45       0.47619048]


In [26]:
c1=np.arange(22,40)

print(c1)
print(f"Summation of c1 is {np.sum(c1)}")
print(f"Mean of c1 is {np.mean(c1)}")
print(f"Minimum of c1 is {np.min(c1)}")
print(f"Maximum of c1 is {np.max(c1)}")

[22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
Summation of c1 is 549
Mean of c1 is 30.5
Minimum of c1 is 22
Maximum of c1 is 39


In [28]:
c2=np.random.randint(0,100,10)

print(c2)
print("Only the first 5 elements:", c2[:5])

[31  2 51  5 67 22 78 70 99 67]
Only the first 5 elements: [31  2 51  5 67]


In [30]:
c3=np.random.randint(0,100,9).reshape(3,3)
print(c3)

print("Only the first 2 rows and 2 columns:\n", c3[:2,:2])

[[22 88  6]
 [ 1 82  2]
 [24 18 42]]
Only the first 2 rows and 2 columns:
 [[22 88]
 [ 1 82]]


In [39]:
c4=np.random.randint(0,100,16)
print(c4)
for i in c4:
    if i%2==0:
        c4[c4==i]=0
print(c4)

[69 48 77 51 46 64 55 13 68 29 19 57 47 74  5 74]
[69  0 77 51  0  0 55 13  0 29 19 57 47  0  5  0]
